Feat/scheduling(scheduler): add workload management and scheduler functionalities
Kuruyia/orka pull request #2
Opened 2023-08-28 09:57 UTC by Assstra

### Change log :

#1st Block : 
- [ ] Map node agent workload status type to controller workload status type
- [ ] Send back workload status stream to controller

#2nd Block : 
- [ ] Map controller workload type to node agent workload type
- [ ] Choose node agent (random at first)
- [ ] WIP : Choose best node agent depending on resources usage

#3rd Block :
- [ ] Use create function to send a workload to node agent
- [ ] Retrieve workload status and send back to controller

2023-08-28 09:59 UTC, Assstra commented
Feel free to comment. I'm pretty sure my code is bad so I'm gonna try to fix everything on Tuesday 29th.
(I don't know how you write good PR's so ...)

2023-08-28 19:41 UTC, BioTheWolff submitted a review, later dismissed
Overall a good PR. I have noted a few improvements, accompanied with code suggestions, to get you on your way!

Be aware that you are missing a few data structures. They *will* come in handy when you try to implement the `signal` function, which is coming in a PR soon. Try to think of a way to keep track of scheduled workloads, consistently and across functions!

2023-08-28 19:41 UTC, BioTheWolff commented on scheduler/src/managers/node_agent/manager.rs
> +    }
In order to add consistency, the function needs to take input of a `&self`, else this will borrow the manager and make it unusable later on in the calling function. I went the Iterator route, although you might want to do it another way. The suggestion below is the one used while implementing the suggestion for the `schedule` function.

```suggestion
    pub fn get_agents(&self) -> Iter<'_, String, NodeAgent> {
        return self.agents.iter();
    }
```

2023-08-28 19:41 UTC, BioTheWolff commented on scheduler/src/grpc/agent_workload_service.rs
> +pub async fn create(workload: Workload) -> Result<(), Box<dyn std::error::Error>> {
As explained further in the comments regarding the `schedule` function, this function should return a `Result<Streaming<WorkloadStatus>, Status>`. This enables better and clearer communication, whilst also forwarding errors that can be nicely caught and raised outside of this function.

I will let you implement the function to match the signature.

```suggestion
pub async fn create(workload: Workload) -> Result<Streaming<WorkloadStatus>, Status> {
```

2023-08-28 19:41 UTC, BioTheWolff commented on scheduler/src/managers/scheduler/mod.rs
Since the main focus of the structure are the workloads (or workload instances), I would prefer you rename the whole folder into `workload`.

2023-08-28 19:41 UTC, BioTheWolff commented on scheduler/src/managers/scheduler/schedule.rs
Following my recommendation on the folder rename (see `managers/scheduler/mod.rs`), I would also advise to rename this file to something clearer, i.e. `mapper`.

2023-08-28 19:41 UTC, BioTheWolff commented on scheduler/src/managers/scheduler/schedule.rs
> +    SchedulingRequest, WorkloadStatus as SchedulerWorkloadStatus,
The workload status is sent to, and handled by, the Controller. I would advise renaming it here, and in other places in this file.

```suggestion
    SchedulingRequest, WorkloadStatus as ControllerWorkloadStatus,
```

2023-08-28 19:41 UTC, BioTheWolff commented on scheduler/src/managers/scheduler/schedule.rs
> +        resource: None, // TO CHANGE
Please do not forget this. You should add a `FIXME` mention so it gets picked up by your IDE, if you are using one.

2023-08-28 19:41 UTC, BioTheWolff commented on scheduler/src/managers/scheduler/schedule.rs
> +    return workload.ok_or(SchedulerError::InvalidWorkload("".to_string()));
The `InvalidWorkload` takes a parameter as input, that seems to be the problematic workload. It would be very advisable to actually input said workload, instead of an empty string. For now, I think the debug string should do.

2023-08-28 19:41 UTC, BioTheWolff commented on scheduler/src/managers/scheduler/schedule.rs
> +    return controller_workload;
In this function, as well as others, you should use the "last expression return" ([Rust lang doc](https://doc.rust-lang.org/std/keyword.return.html)) to produce clearer code.
I also suggest an improvement in the way you handle agent resource mapping.

```suggestion
    SchedulerWorkloadStatus {
        name: agent_workload.name,
        status_code: agent_workload.status,
        message: agent_workload.message,
        resource_usage: agent_workload.resource.map(|r| {
            let usage = r.usage;
            Resources {
                cpu: usage.unwrap_or_default().cpu,
                memory: usage.unwrap_or_default().memory,
                disk: usage.unwrap_or_default().disk,
            }
        }),
    }
```

2023-08-28 19:44 UTC, Assstra commented on scheduler/src/grpc/controller_scheduling_service.rs
>  };
I strongly agree on this one

2023-08-28 21:36 UTC, Assstra commented on scheduler/src/managers/scheduler/schedule.rs
> +    return controller_workload;
Done

2023-08-28 21:38 UTC, Assstra commented on scheduler/src/managers/scheduler/schedule.rs
> +    return workload.ok_or(SchedulerError::InvalidWorkload("".to_string()));
This is the solution i found but i'm not sure of it :
`return workload.clone().ok_or(WorkloadError::InvalidWorkload(
        workload.unwrap_or_default().name.to_string(),
    ));`

2023-08-28 21:40 UTC, Assstra commented on scheduler/src/managers/scheduler/schedule.rs
Done

2023-08-28 21:42 UTC, Assstra commented on scheduler/src/grpc/controller_scheduling_service.rs
>  };
Done

2023-08-28 21:53 UTC, Assstra commented on scheduler/src/managers/node_agent/manager.rs
> +    }
I think i understand but what is this interest ? Security purposes ?

2023-08-28 21:58 UTC, Assstra commented on scheduler/src/grpc/agent_workload_service.rs
> +pub async fn create(workload: Workload) -> Result<(), Box<dyn std::error::Error>> {
Of course !

2023-08-29 09:29 UTC, BioTheWolff commented on scheduler/src/managers/scheduler/schedule.rs
> +    return workload.ok_or(SchedulerError::InvalidWorkload("".to_string()));
As demonstrated privately, the implementation can be reworked in a single match statement. I will leave that work to you.

2023-08-29 09:36 UTC, Kuruyia commented on scheduler/src/managers/node_agent/manager.rs
> +    }
Nope, it's for the purpose of abstraction. The outside world doesn't need to care about what collection you use (in this case, a `HashMap`) to store the agents : you only need to give them what they need, which is a way to iterate through the agents you have stored.
That way, if you need to change this collection type in the future, you won't need to change this function signature, which means you don't change this exposed interface, which finally means that you won't break outside code.

2023-08-29 12:29 UTC, Assstra commented on scheduler/src/managers/scheduler/schedule.rs
> +    return workload.ok_or(SchedulerError::InvalidWorkload("".to_string()));
Done

2023-08-30 18:08 UTC, Kuruyia requested changes
Very good work so far! 👍

2023-08-30 18:08 UTC, Kuruyia commented on scheduler/src/managers/node_agent/metrics.rs
> +    /// Get the Agent's id.
Nit (agent is spelled lowercase everywhere else)
```suggestion
    /// Get the agent's id.
```

2023-08-30 18:08 UTC, Kuruyia commented on scheduler/src/managers/node_agent/metrics.rs
> +    /// This is the URL that should be used to contact its gRPC server.
Nit (agent is spelled lowercase everywhere else)
```suggestion
    /// Get the agent's server address.
    /// This is the URL that can be used to contact its gRPC server.
```

2023-08-30 18:08 UTC, Kuruyia commented on scheduler/src/managers/node_agent/metrics.rs
> +    }
Remove the `get_` prefix. Return a borrowed string instead.
```suggestion
    pub fn address(&self) -> &str {
        self.address
    }
```

2023-08-30 18:08 UTC, Kuruyia commented on scheduler/src/managers/workload/manager.rs
> +    /// Creates a new workload manager
Nit
```suggestion
    /// Creates a new workload manager.
```

2023-08-30 18:08 UTC, Kuruyia commented on scheduler/src/managers/workload/manager.rs
> +    /// Add a new instance to the list
Doc
```suggestion
    /// Add a new instance to the list.
    ///
    /// # Arguments
    ///
    /// * `instance_id` - The ID of the workload instance to add.
    /// * `agent_id` - The ID of the node agent where this workload instance is running.
```

2023-08-30 18:08 UTC, Kuruyia commented on scheduler/src/managers/workload/manager.rs
> +    pub fn add_instance(&mut self, instance_id: &String, agent_id: String) {
Take string slices instead.
```suggestion
    pub fn add_instance(&mut self, instance_id: &str, agent_id: &str) {
```

2023-08-30 18:08 UTC, Kuruyia commented on scheduler/src/managers/workload/manager.rs
> +    pub fn find_related_agent(&self, instance_id: &String) -> Option<&String> {
Take a string slice instead.
```suggestion
    pub fn find_related_agent(&self, instance_id: &str) -> Option<&String> {
```

2023-08-30 18:08 UTC, Kuruyia commented on scheduler/src/managers/workload/manager.rs
> +
Doc
```suggestion

/// Find the node agent associated with a workload instance.
///
/// # Arguments
///
/// * `instance_id` - The ID of the workload instance to find the associated node agent with.
```

2023-08-31 08:14 UTC, Kuruyia approved these changes

2023-08-31 13:42 UTC, Kuruyia requested changes

2023-08-31 13:42 UTC, Kuruyia commented on scheduler/src/managers/node_agent/metrics.rs
> +    }
Please rename the method and use `format!` instead.
```suggestion
    pub fn grpc_url(&self) -> String {
        format!("http://{}", self.address.to_string())
    }
```

2023-08-31 13:46 UTC, BioTheWolff commented on scheduler/src/managers/node_agent/metrics.rs
> +    }
Done! Sorry, that was yucky

2023-08-31 16:19 UTC, Kuruyia approved these changes

2023-08-31 16:21 UTC, merged